name: Build

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  linux:    
    name: build on linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Show dotnet Version
      run: dotnet --version  
    - name: Build with dotnet
      run: |        
        dotnet build --configuration Release --source https://api.nuget.org/v3/index.json Ocelot.Cache.EasyCaching.sln
    - name: Test with dotnet
      run: |
        dotnet test test/Ocelot.Cache.EasyCaching.UnitTests/Ocelot.Cache.EasyCaching.UnitTests.csproj  --no-restore
